// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YangXuAPI.Data;

namespace YangXuAPI.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    [Migration("20200520071258_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("YangXuAPI.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Industry")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Introduction")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Product")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Industry = "Software",
                            Introduction = "Great Company",
                            Name = "Microsoft",
                            Product = "Software"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Industry = "Internet",
                            Introduction = "Don't be evil",
                            Name = "Google",
                            Product = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Country = "China",
                            Industry = "Internet",
                            Introduction = "Fubao Company",
                            Name = "Alipapa",
                            Product = "Software"
                        },
                        new
                        {
                            Id = 4,
                            Country = "China",
                            Industry = "ECommerce",
                            Introduction = "From Shenzhen",
                            Name = "Tencent",
                            Product = "Software"
                        },
                        new
                        {
                            Id = 5,
                            Country = "China",
                            Industry = "Internet",
                            Introduction = "From Beijing",
                            Name = "Baidu",
                            Product = "Software"
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            Industry = "Software",
                            Introduction = "Photoshop?",
                            Name = "Adobe",
                            Product = "Software"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Industry = "Technology",
                            Introduction = "Wow",
                            Name = "SpaceX",
                            Product = "Rocket"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Italy",
                            Industry = "Football",
                            Introduction = "Football Club",
                            Name = "AC Milan",
                            Product = "Football Match"
                        },
                        new
                        {
                            Id = 9,
                            Country = "China",
                            Industry = "ECommerce",
                            Introduction = "From Jiangsu",
                            Name = "Suning",
                            Product = "Goods"
                        },
                        new
                        {
                            Id = 10,
                            Country = "USA",
                            Industry = "Internet",
                            Introduction = "Blocked",
                            Name = "Twitter",
                            Product = "Tweets"
                        },
                        new
                        {
                            Id = 11,
                            Country = "USA",
                            Industry = "Internet",
                            Introduction = "Blocked",
                            Name = "Youtube",
                            Product = "Videos"
                        },
                        new
                        {
                            Id = 12,
                            Country = "China",
                            Industry = "Security",
                            Introduction = "- -",
                            Name = "360",
                            Product = "Security Product"
                        },
                        new
                        {
                            Id = 13,
                            Country = "China",
                            Industry = "ECommerce",
                            Introduction = "Brothers",
                            Name = "Jingdong",
                            Product = "Goods"
                        },
                        new
                        {
                            Id = 14,
                            Country = "China",
                            Industry = "Internet",
                            Introduction = "Music?",
                            Name = "NetEase",
                            Product = "Songs"
                        },
                        new
                        {
                            Id = 15,
                            Country = "USA",
                            Industry = "ECommerce",
                            Introduction = "Store",
                            Name = "Amazon",
                            Product = "Books"
                        },
                        new
                        {
                            Id = 16,
                            Country = "USA",
                            Industry = "Internet",
                            Introduction = "Not Exists?",
                            Name = "AOL",
                            Product = "Website"
                        },
                        new
                        {
                            Id = 17,
                            Country = "USA",
                            Industry = "Internet",
                            Introduction = "Who?",
                            Name = "Yahoo",
                            Product = "Mail"
                        },
                        new
                        {
                            Id = 18,
                            Country = "USA",
                            Industry = "Internet",
                            Introduction = "Is it a company?",
                            Name = "Firefox",
                            Product = "Browser"
                        });
                });

            modelBuilder.Entity("YangXuAPI.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "00001",
                            FirstName = "Nick",
                            Gender = 2,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            DateOfBirth = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "00002",
                            FirstName = "Linda",
                            Gender = 1,
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "00003",
                            FirstName = "Crole",
                            Gender = 1,
                            LastName = "Fories"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            DateOfBirth = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "00004",
                            FirstName = "Kobe",
                            Gender = 2,
                            LastName = "Brant"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "00005",
                            FirstName = "Dora",
                            Gender = 1,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 3,
                            DateOfBirth = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "00006",
                            FirstName = "Jack",
                            Gender = 2,
                            LastName = "Ma"
                        });
                });

            modelBuilder.Entity("YangXuAPI.Entities.Employee", b =>
                {
                    b.HasOne("YangXuAPI.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
